const themeoptions = () => {
    return {
        colors: {
            primary_main: '#902fa1',
            primary_light: '#FFFAE6',
            primary_light1: '#FEFBEC',
            primary_light2: '#fdeb7e',
            primary_main1: '#6c2379',
            secondary_main: '#000000',
            background: '#f0f1f2',
            dialog: '#3e0148',
            btnbg: '#3F3F3F',
            primarybtnbg: '#59AB2B',
            icon: '#BABABA',
            error: '#ED3833',
            greytext: '#676767',
            contrastText: '#fff',
            header: '#3e0148',
            tabs: '#f0f1f2',
            textcolor: '#000',
            activetext: '#fff',
            activeTabtext: '#fff',
            dialogtitle: '#fff',
            headertext: '#ec92fc',
            outlinedborder: '#902fa1',
            dialogcontent: '#fff',
            greytext: '#666666',
            checkcircle: '#77d405',
            disabled: '#949494',
            shadedbtn: '#902fa1',
            secondaryborder: '#dddddd',
            formbg: '#f4f4f4',
            headerDivider: '#333333',
            betslip: '#111111',
            legs: '#2c2c2c',
            betslipicon: '#7d7c7c',
            bgalertinfo: '#E7E6E6',
            textalertinfo: '#8EBDE2',
            multilegs: '#343434',
        },
        fonts: {},
    };
};

export default themeoptions;
